### ISSUE TITLE
DLLs

### ISSUE THREAD

**Issue by ManxOne** [nebarnix/PDT-TelemetryExplorer#1]
Hello, I've not had much experience with this kinda thing and tried running the program and it says it needs a million and a half DLLs. No idea where to start. I had a similar problem with "Project Desert Tortoise" but it was only missing 4 so I just threw them in the same folder and it worked, but this one needs too many for me to do that. Thanks in advance.

**Comment by nebarnix** [comment]
You're right. I used QT to compile this, so you'll need the QT redistributable DLLs. I'll come up with a list and some links.

**Comment by nebarnix** [comment]
OK, I found the exact QT5 DLL dependancies and uploaded just those to the folder. They have been re-compiled to support qwt so just doing a QT5 install probably won't work. 

Let me know when you test it out!

**Comment by nebarnix** [comment]
Fixed!
