### ISSUE TITLE
Cannot launch

### ISSUE THREAD

**Issue by bigjohn2345** [nebarnix/PDT-TelemetryExplorer#2]
When I try to launch the "TelemExplorer.exe" executable, it does not start and I get an error message (shown).
![image](https://user-images.githubusercontent.com/15947236/43040006-d480aa94-8cfe-11e8-904b-cd0736900ef2.png)
Any help would be appreciated.

**Comment by bigjohn2345** [comment]
![image](https://user-images.githubusercontent.com/15947236/43040024-115171ba-8cff-11e8-9ac8-37f2cfa4317d.png)
I also get this on clicking "OK"

**Comment by nebarnix** [comment]
Fixed!
