### ISSUE TITLE
Fix the DLLs

### ISSUE THREAD

**Issue by melvin2204** [nebarnix/PDT-TelemetryExplorer#3]
It has been a year since the last issue report and the dev still hasn't fixed it. I'm getting the same 'this application failed to start because it could not find or load the qt platform plugin windows' message. It seems like this project is dead. Incase someone knows a solution, please report it.

**Comment by nebarnix** [comment]
ah HAH! I needs a windows DLL! I

**Comment by nebarnix** [comment]
Fixed!
